/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: ['intro'],
  businessSidebar: [{ type: 'autogenerated', dirName: 'business'}],
  designSidebar: [{ type: 'autogenerated', dirName: 'design'}],
  frontendSidebar: [{ type: 'autogenerated', dirName: 'frontend' }],
  backendSidebar: [{ type: 'autogenerated', dirName: 'backend' }],
  devopsSidebar: [{ type: 'autogenerated', dirName: 'devops' }],
  philosophySidebar: [{ type: 'autogenerated', dirName: 'philosophy' }],
  cheatsheetSidebar: [{ type: 'autogenerated', dirName: 'cheatsheets' }],
  coffeeSidebar: [{ type: 'autogenerated', dirName: 'coffee' }]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
